spring:
  datasource:
    url: ${DB.URL}
    driver-class-name: org.h2.Driver
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
  h2:
    console:
      enabled: true

  application:
    name: sejong

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    '[com.mtvs]': debug
    '[org.hibernate.type]': trace

jwt:
  secret: ${JWT.SECRET}

server:
  port: 7878