spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ohgiraffers
    password: ohgiraffers
#  h2:
#    console:
#      enabled: true
#
#  application:
#    name: sejong

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    '[com.mtvs]': debug
    '[org.hibernate.type]': trace